#!/bin/bash

# Dependencies: curl, alsa-utils, xorg-setxkbmap
wea=$(curl wttr.in/xiaoshan?format="%C+%t")

while true;
do
    kbl=$(setxkbmap -query | awk '/layout/{print $2}')
    vol=$(amixer get Master | tail -1 | awk '{print$4}')
    bat=$(cat /sys/class/power_supply/BAT1/capacity)
    batterystate=$(cat /sys/class/power_supply/BAT1/status)
    if [ "$batterystate" = "Discharging" ]; then
        bat=≠$bat
    elif [ $b -gt 90 ];then
        bat=
    else
        bat==$bat
    fi
    d=$(date '+%Y%m%d %^a %H:%M:%S.%N')
    xsetroot -name "$kbl $bat ★$vol $wea ${d:0:23}"
    sleep 0.1
done


# vim:ft=bash:
